path: /Users/ajeebrimal/Documents/Masters Thesis/aerial-satellite-imagery-segmentation-nepal/output/512x512
train: images/train
val: images/val
test: images/test

names:
  0: background
  1: building
  2: woodland